=== zacharyejohnson/regai-grading/regai-scorm-frontend/regai-i-scorm-frontend/public/scorm/imscp_rootv1p1p2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:imscp="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
            elementFormDefault="qualified"
            version="IMS CP 1.1.2">

    <xsd:element name="manifest">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="imscp:metadata" minOccurs="0"/>
                <xsd:element ref="imscp:organizations"/>
                <xsd:element ref="imscp:resources"/>
            </xsd:sequence>
            <xsd:attribute name="identifier" type="xsd:ID" use="required"/>
            <xsd:attribute name="version" type="xsd:string" use="optional"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="metadata">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="schema" type="xsd:string"/>
                <xsd:element name="schemaversion" type="xsd:string"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="organizations">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="imscp:organization" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="default" type="xsd:IDREF" use="optional"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="organization">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="title" type="xsd:string"/>
                <xsd:element ref="imscp:item" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="identifier" type="xsd:ID" use="required"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="item">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="title" type="xsd:string"/>
            </xsd:sequence>
            <xsd:attribute name="identifier" type="xsd:ID" use="required"/>
            <xsd:attribute name="identifierref" type="xsd:string" use="optional"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="resources">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="imscp:resource" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="resource">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="imscp:file" maxOccurs="unbounded"/>
            </xsd:sequence>
            <xsd:attribute name="identifier" type="xsd:ID" use="required"/>
            <xsd:attribute name="type" type="xsd:string" use="required"/>
            <xsd:attribute name="href" type="xsd:anyURI" use="optional"/>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="file">
        <xsd:complexType>
            <xsd:attribute name="href" type="xsd:anyURI" use="required"/>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== zacharyejohnson/regai-grading/regai-scorm-frontend/public/scorm/imsmanifest.xml
<?xml version="1.0" standalone="no" ?>
<manifest identifier="com.example.assignment" version="1"
          xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
          xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_rootv1p2"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.imsproject.org/xsd/imscp_rootv1p1p2 imscp_rootv1p1p2.xsd
                              http://www.imsglobal.org/xsd/imsmd_rootv1p2p1 imsmd_rootv1p2p1.xsd
                              http://www.adlnet.org/xsd/adlcp_rootv1p2 adlcp_rootv1p2.xsd">
  <metadata>
    <schema>ADL SCORM</schema>
    <schemaversion>1.2</schemaversion>
  </metadata>
  <organizations default="default_org">
    <organization identifier="default_org">
      <title>Assignment Title</title>
      <item identifier="item_1" identifierref="resource_1">
        <title>Assignment Content</title>
      </item>
    </organization>
  </organizations>
  <resources>
    <resource identifier="resource_1" type="webcontent" adlcp:scormtype="sco" href="content/index.html">
      <file href="content/index.html"/>
      <file href="shared/scripts/scorm_api_wrapper.js"/>
      <file href="shared/scripts/api_service.js"/>
      <file href="scripts/main.js"/>
      <file href="shared/styles/main.css"/>
    </resource>
  </resources>
</manifest>
